AWSTemplateFormatVersion: '2010-09-09'

 # aws cloudformation create-stack \
 # --stack-name HazelCastRoles \
 # --template-body file://roles.yaml \
 # --capabilities CAPABILITY_IAM

Resources:

  ECSforEC2Role:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ECSforECSPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - ec2:DescribeTags
                  - ecs:CreateCluster
                  - ecs:DeregisterContainerInstance
                  - ecs:DiscoverPollEndpoint
                  - ecs:Poll
                  - ecs:RegisterContainerInstance
                  - ecs:StartTelemetrySession
                  - ecs:UpdateContainerInstancesState
                  - ecs:Submit*
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"

  ECSAutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Action:
            - "sts:AssumeRole"
          Effect: Allow
          Principal:
            Service:
              - application-autoscaling.amazonaws.com
      Path: /
      Policies:
        - PolicyName: ecs-service-autoscaling
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - application-autoscaling:*
                - cloudwatch:DescribeAlarms
                - cloudwatch:PutMetricAlarm
                - ecs:DescribeServices
                - ecs:UpdateService
              Resource: "*"

  HazelTaskRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: HazelTaskExecution
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - ecs:ListTasks
                  - ecs:DescribeTasks
                  - ec2:DescribeNetworkInterfaces
                  - logs:CreateLogGroup

  HazelExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"

Outputs:

  TaskRoleArn:
    Value: !GetAtt HazelTaskRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ECSTaskRoleArn"

  TaskRole:
    Value: !Ref HazelTaskRole
    Export:
      Name: !Sub "${AWS::StackName}-ECSTaskRole"

  ExecutionRoleArn:
    Value: !GetAtt HazelExecutionRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ECSExecutionRoleArn"

  ExecutionRole:
    Value: !Ref HazelExecutionRole
    Export:
      Name: !Sub "${AWS::StackName}-ECSExecutionRole"

  ECSforEC2RoleArn:
    Value: !GetAtt ECSforEC2Role.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ECSforEC2RoleArn"

  ECSforEC2Role:
    Value: !Ref ECSforEC2Role
    Export:
      Name: !Sub "${AWS::StackName}-ECSforEC2Role"

  ECSAutoScalingRoleArn:
    Value: !GetAtt ECSAutoScalingRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ECSAutoScalingRoleArn"

  ECSAutoScalingRole:
    Value: !Ref ECSAutoScalingRole
    Export:
      Name: !Sub "${AWS::StackName}-ECSAutoScalingRole"